language: python
python:
  - "2.7.10"
install:
  - pip install -r requirements.txt
  - pip install https://pypi.python.org/packages/2.6/P/PyHamcrest/PyHamcrest-1.9.0-py2.6.egg
script:
  - python --version
  - behave --junit
